# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

source 'https://gitlab.linphone.org/BC/public/podspec.git'
source 'https://cdn.cocoapods.org/'

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'SipApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Linphone SDK - mesma versão do Android (5.3.x)
  pod 'linphone-sdk', '~> 5.3.0'

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    
    # Fix Linphone C++ conflicts
    swift_file = "#{installer.sandbox.root}/linphone-sdk/linphone-sdk/apple-darwin/share/linphonesw/LinphoneWrapper.swift"
    if File.exist?(swift_file)
      File.write(swift_file, "// File disabled to avoid C++ conflicts\n")
    end
    
    # Ensure deployment target
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    end
  end
end
